### ISSUE TITLE
release version can't load model 

### ISSUE THREAD

**Issue by captain-miao** [libxposed/example#3]
```
 java.lang.NoSuchMethodException: xxxxxx.<init> [class io.github.libxposed.api.XposedContext, interface io.github.libxposed.api.XposedModuleInterface$ModuleLoadedParam]
 	at java.lang.Class.getConstructor0(Class.java:2332)
 	at java.lang.Class.getConstructor(Class.java:1728)
 	at I.g(Unknown Source:314)
 	at miCBTdjZUcLiiEL.WG.xJV.XposedInit.lambda$loadModules$1(Unknown Source:11)
 	at miCBTdjZUcLiiEL.WG.xJV.XposedInit.a(Unknown Source:0)
 	at F0.accept(Unknown Source:4)
 	at java.util.ArrayList.forEach(ArrayList.java:1262)
 	at miCBTdjZUcLiiEL.WG.xJV.XposedInit.loadModules(Unknown Source:11)
 	at f.afterHookedMethod(Unknown Source:267)
 	at miCBTdjZUcLiiEL.WG.xJV.XposedBridge$AdditionalHookInfo.callback(Unknown Source:175)
 	at LSPHooker_.attach(Unknown Source:22)
 	at android.app.ActivityThread.main(ActivityThread.java:7997)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

Does the io.github.libxposed.api package need to be keep? It's strange that there's no problem with the debug version.

[lsp-example-app-release.apk.zip](https://github.com/libxposed/example/files/11818393/lsp-example-app-release.apk.zip)
[LSPosed_2023-06-21T21_28_47.603.zip](https://github.com/libxposed/example/files/11818411/LSPosed_2023-06-21T21_28_47.603.zip)

**Comment by captain-miao** [comment]
I'm not sure what caused it, but now there is no problem.
1. Removed getSharedPreferences(name, Context.MODE_WORLD_READABLE);
2. Made some changes to the code.
